### ISSUE TITLE
A robust and efficient framework for sports field registration

### ISSUE THREAD

**Issue by dllu** [cemunds/awesome-sports-camera-calibration#3]
Should add this new paper: https://www.amazon.science/publications/a-robust-and-efficient-framework-for-sports-field-registration

**Comment by cemunds** [comment]
Thank you for your contribution. I'll have a look at the paper soon and then add it to the list.

**Comment by cemunds** [comment]
I finally got around to reading the paper and I added it to the list. Thank you again, I think it makes for a good addition.
